---
title: "An Analysis of Prison Population Rates"
output: html_document
---

```{r setup, include=FALSE}
source("analysis.R")
```

## R Markdown
The systemic oppression of minorities, particularly African Americans, in the American prison system continues to be exposed through effective data analytics. This report seeks to analyze prison population rates, both across racial groups and states. In this report, I primarily work with variables related to prison population rates. The total prison population rate variable is based on the number of people held in state prison on December 31 of a given year in relation to the total population of the county of commitment. Similarly, this variable can be disaggreated to express the rate that specific racial groups are committed to state prisons.
In generating this report, several values of interest emerged. First, the state with the highest average rate of Black imprisonment is Nebraska. Furthermore, the county with the highest average rate of Black imprisonment is McPherson County, also located in Nebraska. The state with the lowest average rate of Black imprisonment was found to be Hawaii. Across all states, the average rate of Black imprisonment was calculated to be approximately 2785.15. Comparing this national average across a 10 year period, from 1996 to 2016, revealed an increase of 115.27.


